### ISSUE TITLE
Please upload newest version to Chrome Web Store

### ISSUE THREAD

**Issue by Annonomus-Penguin** [Manishearth/AnnoTabe#14]
I'm pretty sure no one reads these things anyway, so I decided to ramble on for a bit here. I'm not sure if you should be using a magical electricity box thingy if you don't understand the title (given that you speak English). :D

A short haiku for you--

> The quick brown fox jumped
> over the lazy doggy
> and that's it for now.

**Comment by Annonomus-Penguin** [comment]
Dang it, I messed up the haiku the first time :joy:

**Comment by Manishearth** [comment]
haha. I need to fix my Github notification story, but sadly my uni blocks SMTP so I can't use thinderbird (and gmail doesn't know how to filter by header).

blargh.

**Comment by Annonomus-Penguin** [comment]
Perhaps another extension that filters GitHub notifications?!?! 😀
